baseURL = "http://christophermcdowell.dev/"
languageCode = "en-us"
title = "Christopher McDowell's Blog"

[params]
  Name = "Christopher McDowell"
  HeaderUsername = "chris"
  HeaderHostname = "christophermcdowell.dev"
  About = "info_about_you"
  ProfilePicture = "profile_picture_url"
